package com.iispl.banksettlement.entity;

import com.iispl.banksettlement.enums.NetDirection;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * NettingPosition — Net bilateral settlement position between two banks
 * for a given currency on a given date.
 *
 * FIELDS (exact from document):
 *   positionId         — primary key
 *   counterpartyBankId — FK to bank table (the OTHER bank in this pair)
 *   currency           — "INR"
 *   grossDebitAmount   — total amount this bank paid TO counterparty
 *   grossCreditAmount  — total amount this bank received FROM counterparty
 *   netAmount          — grossCreditAmount - grossDebitAmount
 *   direction          — NET_CREDIT (we receive), NET_DEBIT (we pay), FLAT
 *   positionDate       — the date of this netting cycle
 *
 * EXTRA FIELDS (added for clarity):
 *   fromBankName / toBankName — human-readable names for the two banks
 *
 * HOW IT IS COMPUTED:
 *   For every settled transaction between BankA and BankB:
 *     grossDebitAmount  += amount where fromBank = BankA (BankA sent money)
 *     grossCreditAmount += amount where toBank   = BankA (BankA received money)
 *   netAmount = grossCreditAmount - grossDebitAmount
 *   If netAmount > 0 → BankA is NET_CREDIT (receives money from BankB)
 *   If netAmount < 0 → BankA is NET_DEBIT  (pays money to BankB)
 *   If netAmount = 0 → FLAT
 *
 * TABLE: netting_position
 */
public class NettingPosition {

    // Primary key — auto generated by DB
    private Long positionId;

    // FK to bank table — the counterparty bank in this bilateral pair.
    // Example: if this position is "HDFC vs SBI", counterpartyBankId = SBI's bank_id
    private Long counterpartyBankId;

    // Full name of the bank that is the PAYER in this position
    private String fromBankName;

    // Full name of the bank that is the RECEIVER in this position
    private String toBankName;

    // ISO 4217 currency code — always "INR" for our system
    private String currency;

    // Total amount sent FROM fromBank TO toBank across all settled transactions
    private BigDecimal grossDebitAmount;

    // Total amount received BY fromBank FROM toBank across all settled transactions
    private BigDecimal grossCreditAmount;

    // Net amount = grossCreditAmount - grossDebitAmount
    // Positive → fromBank receives (NET_CREDIT)
    // Negative → fromBank pays    (NET_DEBIT)
    // Zero     → no net movement  (FLAT)
    private BigDecimal netAmount;

    // NET_CREDIT, NET_DEBIT, or FLAT
    private NetDirection direction;

    // The date of this netting cycle
    private LocalDate positionDate;

    // Timestamp when this position was calculated
    private LocalDateTime createdAt;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    public NettingPosition() {
        this.grossDebitAmount  = BigDecimal.ZERO;
        this.grossCreditAmount = BigDecimal.ZERO;
        this.netAmount         = BigDecimal.ZERO;
        this.direction         = NetDirection.FLAT;
        this.currency          = "INR";
        this.positionDate      = LocalDate.now();
        this.createdAt         = LocalDateTime.now();
    }

    public NettingPosition(Long counterpartyBankId, String fromBankName, String toBankName,
                           BigDecimal grossDebitAmount, BigDecimal grossCreditAmount,
                           BigDecimal netAmount, NetDirection direction, LocalDate positionDate) {
        this.counterpartyBankId = counterpartyBankId;
        this.fromBankName       = fromBankName;
        this.toBankName         = toBankName;
        this.grossDebitAmount   = grossDebitAmount;
        this.grossCreditAmount  = grossCreditAmount;
        this.netAmount          = netAmount;
        this.direction          = direction;
        this.positionDate       = positionDate;
        this.currency           = "INR";
        this.createdAt          = LocalDateTime.now();
    }

    // -----------------------------------------------------------------------
    // Getters and Setters
    // -----------------------------------------------------------------------

    public Long getPositionId() { return positionId; }
    public void setPositionId(Long positionId) { this.positionId = positionId; }

    public Long getCounterpartyBankId() { return counterpartyBankId; }
    public void setCounterpartyBankId(Long counterpartyBankId) { this.counterpartyBankId = counterpartyBankId; }

    public String getFromBankName() { return fromBankName; }
    public void setFromBankName(String fromBankName) { this.fromBankName = fromBankName; }

    public String getToBankName() { return toBankName; }
    public void setToBankName(String toBankName) { this.toBankName = toBankName; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    public BigDecimal getGrossDebitAmount() { return grossDebitAmount; }
    public void setGrossDebitAmount(BigDecimal grossDebitAmount) { this.grossDebitAmount = grossDebitAmount; }

    public BigDecimal getGrossCreditAmount() { return grossCreditAmount; }
    public void setGrossCreditAmount(BigDecimal grossCreditAmount) { this.grossCreditAmount = grossCreditAmount; }

    public BigDecimal getNetAmount() { return netAmount; }
    public void setNetAmount(BigDecimal netAmount) { this.netAmount = netAmount; }

    public NetDirection getDirection() { return direction; }
    public void setDirection(NetDirection direction) { this.direction = direction; }

    public LocalDate getPositionDate() { return positionDate; }
    public void setPositionDate(LocalDate positionDate) { this.positionDate = positionDate; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    // -----------------------------------------------------------------------
    // toString
    // -----------------------------------------------------------------------

    @Override
    public String toString() {
        return "NettingPosition{positionId=" + positionId
                + ", fromBankName='" + fromBankName + '\''
                + ", toBankName='" + toBankName + '\''
                + ", grossDebitAmount=" + grossDebitAmount
                + ", grossCreditAmount=" + grossCreditAmount
                + ", netAmount=" + netAmount
                + ", direction=" + direction
                + ", positionDate=" + positionDate + '}';
    }
}