package com.iispl.banksettlement.entity;

import com.iispl.banksettlement.enums.ReconStatus;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * ReconciliationEntry — Compares expected vs actual NPCI bank account balance
 * after a netting cycle and records whether they match.
 *
 * FIELDS (exact from document):
 *   entryId             — primary key
 *   reconciliationDate  — date this reconciliation was run
 *   accountId           — FK to npci_bank_account.npci_account_id
 *   expectedAmount      — what the balance should be (opening ± net positions)
 *   actualAmount        — what the balance actually is in DB after netting
 *   variance            — actualAmount - expectedAmount
 *   reconStatus         — MATCHED, UNMATCHED, EXCEPTION, PARTIALLY_MATCHED, PENDING
 *   remarks             — human-readable note explaining the result
 *
 * HOW IT IS COMPUTED (for each NPCI member account):
 *   expectedAmount = openingBalance ± sum of all net positions for that bank
 *   actualAmount   = current_balance in npci_bank_account after update
 *   variance       = actualAmount - expectedAmount
 *   If variance == 0 → MATCHED (everything balanced correctly)
 *   If variance != 0 → UNMATCHED (something went wrong)
 *
 * TABLE: reconciliation_entry
 */
public class ReconciliationEntry {

    // Primary key — auto generated by DB
    private Long entryId;

    // The date this reconciliation was performed
    private LocalDate reconciliationDate;

    // FK to npci_bank_account.npci_account_id
    // (In the document this is account_id — we point it to the NPCI account)
    private Long accountId;

    // Name of the bank this reconciliation entry is for (for display)
    private String bankName;

    // What the balance SHOULD be after applying all netting positions
    private BigDecimal expectedAmount;

    // What the balance ACTUALLY IS in DB after the netting engine ran
    private BigDecimal actualAmount;

    // Difference: actualAmount - expectedAmount
    // Zero means perfectly balanced.
    private BigDecimal variance;

    // Result of reconciliation: MATCHED, UNMATCHED, EXCEPTION etc.
    private ReconStatus reconStatus;

    // Human-readable explanation
    private String remarks;

    // When this entry was created
    private LocalDateTime createdAt;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    public ReconciliationEntry() {
        this.reconciliationDate = LocalDate.now();
        this.reconStatus        = ReconStatus.PENDING;
        this.createdAt          = LocalDateTime.now();
    }

    public ReconciliationEntry(Long accountId, String bankName, BigDecimal expectedAmount,
                                BigDecimal actualAmount, BigDecimal variance,
                                ReconStatus reconStatus, String remarks) {
        this.accountId          = accountId;
        this.bankName           = bankName;
        this.expectedAmount     = expectedAmount;
        this.actualAmount       = actualAmount;
        this.variance           = variance;
        this.reconStatus        = reconStatus;
        this.remarks            = remarks;
        this.reconciliationDate = LocalDate.now();
        this.createdAt          = LocalDateTime.now();
    }

    // -----------------------------------------------------------------------
    // Getters and Setters
    // -----------------------------------------------------------------------

    public Long getEntryId() { return entryId; }
    public void setEntryId(Long entryId) { this.entryId = entryId; }

    public LocalDate getReconciliationDate() { return reconciliationDate; }
    public void setReconciliationDate(LocalDate reconciliationDate) {
        this.reconciliationDate = reconciliationDate;
    }

    public Long getAccountId() { return accountId; }
    public void setAccountId(Long accountId) { this.accountId = accountId; }

    public String getBankName() { return bankName; }
    public void setBankName(String bankName) { this.bankName = bankName; }

    public BigDecimal getExpectedAmount() { return expectedAmount; }
    public void setExpectedAmount(BigDecimal expectedAmount) { this.expectedAmount = expectedAmount; }

    public BigDecimal getActualAmount() { return actualAmount; }
    public void setActualAmount(BigDecimal actualAmount) { this.actualAmount = actualAmount; }

    public BigDecimal getVariance() { return variance; }
    public void setVariance(BigDecimal variance) { this.variance = variance; }

    public ReconStatus getReconStatus() { return reconStatus; }
    public void setReconStatus(ReconStatus reconStatus) { this.reconStatus = reconStatus; }

    public String getRemarks() { return remarks; }
    public void setRemarks(String remarks) { this.remarks = remarks; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    // -----------------------------------------------------------------------
    // toString
    // -----------------------------------------------------------------------

    @Override
    public String toString() {
        return "ReconciliationEntry{entryId=" + entryId
                + ", bankName='" + bankName + '\''
                + ", expectedAmount=" + expectedAmount
                + ", actualAmount=" + actualAmount
                + ", variance=" + variance
                + ", reconStatus=" + reconStatus
                + ", remarks='" + remarks + '\'' + '}';
    }
}