package com.iispl.entity;

/**
 * Bank — Represents a member bank that participates in the settlement system.
 *
 * This is a separate entity from Account (which is a customer's account).
 * Bank is the institution itself — HDFC Bank, SBI Bank etc.
 *
 * The bank_id from this table is used as counterparty_bank_id
 * in the netting_position table (as required by the document).
 *
 * RELATIONSHIP:
 *   Bank HAS-A NpciMemberAccount (one bank has one NPCI settlement account)
 *   NettingPosition.counterpartyBankId → Bank.bankId
 */
public class Bank {

    // Primary key — auto-generated by DB
    private Long bankId;

    // Full name of the bank e.g. "HDFC Bank", "SBI Bank"
    private String bankName;

    // Short IFSC prefix code e.g. "HDFC", "SBIN", "ICIC", "UTIB", "KKBK"
    private String bankCode;

    // Whether this bank is currently an active member
    private boolean isActive;

    // -----------------------------------------------------------------------
    // Constructors
    // -----------------------------------------------------------------------

    public Bank() {
    }

    public Bank(Long bankId, String bankName, String bankCode, boolean isActive) {
        this.bankId   = bankId;
        this.bankName = bankName;
        this.bankCode = bankCode;
        this.isActive = isActive;
    }

    // -----------------------------------------------------------------------
    // Getters and Setters
    // -----------------------------------------------------------------------

    public Long getBankId() { return bankId; }
    public void setBankId(Long bankId) { this.bankId = bankId; }

    public String getBankName() { return bankName; }
    public void setBankName(String bankName) { this.bankName = bankName; }

    public String getBankCode() { return bankCode; }
    public void setBankCode(String bankCode) { this.bankCode = bankCode; }

    public boolean isActive() { return isActive; }
    public void setActive(boolean active) { isActive = active; }

    // -----------------------------------------------------------------------
    // toString
    // -----------------------------------------------------------------------

    @Override
    public String toString() {
        return "Bank{bankId=" + bankId + ", bankName='" + bankName + '\''
                + ", bankCode='" + bankCode + '\'' + ", isActive=" + isActive + '}';
    }
}